type: Scene2D

objects:
  - name: world
    source: drafts/world.yaml

  - name: player_1
    source: drafts/player.yaml
  - name: player_controller_1
    source: drafts/player_controller.yaml
  
  - name: player_2
    source: drafts/player.yaml
  - name: player_controller_2
    source: drafts/player_controller.yaml

stages:
  # PLAYER 1
  - pipeline: SET_PLAYER
    name: player_1
    controller: player_controller_1
    state: RIGHT
    row: 0
    column: 0
  
  # PLAYER 2
  - pipeline: SET_PLAYER
    name: player_2
    controller: player_controller_2
    state: UP
    row: 4
    column: 4
  
  - pipeline: PRINT_WORLD
    delay: 5000

  # %%% ACTION PIPELINE %%%
  - pipeline: PLAYER_ACTION
    name: player_1
    action: FORWARD
  - pipeline: PLAYER_ACTION
    name: player_2
    action: FORWARD

  - pipeline: PLAYER_ACTION
    name: player_1
    action: FORWARD
  - pipeline: PLAYER_ACTION
    name: player_2
    action: TURN_LEFT

  - pipeline: PLAYER_ACTION
    name: player_1
    action: FORWARD
  - pipeline: PLAYER_ACTION
    name: player_2
    action: BACKWARD

pipelines:
  # PIPE: PRINT_WORLD
  - name: PRINT_WORLD
    stages:
      - object: world
        call: print2D
      - object: this
        call: pause
        with: 
          - type: payload
            data: $delay
  # PIPE: SET_PLAYER
  - name: SET_PLAYER
    stages:
      - object: $name
        call: putState
        with:
          - type: payload
            data: $state
      - object: $name
        call: setController2D
        with: 
          - type: object
            name: $controller
      - object: world
        call: addItem2D
        with: 
          - type: object
            name: $name
          - type: payload
            data:
              row: $row
              column: $column
  # PIPE: PLAYER_ACTION
  - name: PLAYER_ACTION
    stages:
      - object: $name
        call: action
        with:
          - type: payload
            data: $action
      - object: world
        call: print2D
        with:
          - type: payload
            data:
              clear: TRUE
      - object: this
        call: pause
        with: 
          - type: payload
            data: 1000
