type: Scene2D

objects:
  - name: game_1
    source: drafts/game_1.yaml

stages:
  - object: game_1
    call: setScene2D
    with:
      - type: object
        name: this
  - object: game_1
    call: loop
  # - object: game_1
  #   call: log
  # - object: this
  #   call: log

pipelines:
  # PIPE: CREATE_PLAYER
  - name: CREATE_PLAYER
    stages:
      - object: this
        call: createObjects
        with:
          - type: payload
            data:
              - name: $name
                source: drafts/player.yaml
              - name: $controller
                source: drafts/player_controller.yaml
      - pipeline: SET_PLAYER
        name: $name
        controller: $controller
        state: $state
        row: $row
        column: $column
  # PIPE: PRINT_WORLD
  - name: PRINT_WORLD
    stages:
      - object: world
        call: print2D
      - object: this
        call: pause
        with: 
          - type: payload
            data: $delay
  # PIPE: SET_PLAYER
  - name: SET_PLAYER
    stages:
      - object: $name
        call: putState
        with:
          - type: payload
            data: $state
      - object: $name
        call: setController2D
        with: 
          - type: object
            name: $controller
      - object: world
        call: addItem2D
        with: 
          - type: object
            name: $name
          - type: payload
            data:
              row: $row
              column: $column
  # PIPE: PLAYER_ACTION
  - name: PLAYER_ACTION
    stages:
      - object: $name
        call: action
        with:
          - type: payload
            data: $action
      - object: world
        call: print2D
        with:
          - type: payload
            data:
              clear: TRUE
      - object: this
        call: pause
        with: 
          - type: payload
            data: 1000
